display_name: AppExample

icon: icon.png

keywords:
  - Hello
  - World
  - Test
  - Application

generic_name: AppExample

categories:
  - Utility

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# fastforge automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []
